name: Deploy to Vercel

on:
  push:
    branches: [main]
    paths:
      - "apps/**"
      - "shared/**"
  pull_request:
    branches: [main]
    paths:
      - "apps/**"
      - "shared/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [template] # ここに新しいアプリを追加

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd apps/${{ matrix.app }}
          npm ci

      - name: Build
        run: |
          cd apps/${{ matrix.app }}
          npm run build

      - name: Deploy to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/${{ matrix.app }}
          vercel-args: "--prod"
        if: github.ref == 'refs/heads/main'

      - name: Deploy Preview
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/${{ matrix.app }}
        if: github.ref != 'refs/heads/main'
